### PR TITLE
Update compiler versions

### PR DESCRIPTION
**Pull request by alxbilger**
according to the latest releases

### CODE REVIEW

**Review by fredroy — COMMENTED** [review]
On the latest Ubuntu LTS (2204) version is 12.2 (and clang 14)
if we want to be consistent with the previous statement that we support the latest LTS...

(as a matter of fact, I would even not set the version in the command if there is no PPA installed anyway)

**Comment by alxbilger** [comment]
If we rely on the gcc version shipped with Ubuntu, why is there even an instruction to install it?

**Comment by fredroy** [comment]
Well at least the command to install it is needed I suppose (it is not installed by default after all)

**Comment by alxbilger** [comment]
I think it is installed by default

**Comment by fredroy** [comment]
> I think it is installed by default

It must have changed in the latest versions then, in 20.04 (and before) you had to install it (either gcc package or the build-essential meta-package)

**Comment by alxbilger** [comment]
I found the information here: https://askubuntu.com/questions/866533/is-gcc-part-of-ubuntu-os

**Comment by fredroy** [comment]
> I found the information here: https://askubuntu.com/questions/866533/is-gcc-part-of-ubuntu-os

weird, maybe i got confused with the docker (server? minimal?) version where you need to install it

**Comment by alxbilger** [comment]
> On the latest Ubuntu LTS (2204) version is 12.2 (and clang 14) if we want to be consistent with the previous statement that we support the latest LTS...

Does it prevent to install a newer version? The sentence was about the latest version

**Comment by fredroy** [comment]
You would need to add any kind of backport or a PPA, I dont recall Ubuntu upgrading the compiler version without a new Ubuntu release (but maybe I am wrong rho 🫢)

**Pull request closed without merging**
